//export const BASE_URL = "ec2-3-14w-10-112.us-east-2.compute.amazonaws.com:8080"
export const BASE_URL = "dhb:8080"
export const LOGIN_URL = "/login"
export const MESSAGE_DOCTOR = "/user/send/doctors"
export const MESSAGE_FRIENDS = "/user/send/friends"
